Squashed import SamsungDoze -> HTCDoze
* squashed for easy testing, full branch available
 https://github.com/jrior001/android_device_htc_msm8960-common/commits/cm-12.1

doze: Add service for using proximity sensor for wake-up

* Added custom service that uses proximity sensor in wake-up mode
  to trigger display on
* If more sensor triggers are suitable to use, they can be added
  to the service

Change-Id: Id0849fb5c17ff569d771a19cebfc579dc93dbc48

doze: Set gesture to disabled by default

Change-Id: I0bf3f6a3a4c01bab7ff7522e916e2149f9cfe8d5

qcom-common: doze: Consolidate doze settings

* Allow user to disable ambient display from gesture panel
* Disable/enable doze settings based on ambient display state

Change-Id: I0ff7686ccc04037b3ada9a8355384ba6746cf30c

qcom-common: doze: fix defaults

Change all defaults to false

Change-Id: I2df507b2fc823d3fb07bce89d44067db565a5ab8

qcom-common: doze: Add back button to action bar

Change-Id: Ia56183c8c2d5a6bc25c84f1d1b9823b84bc936c9

Automatic translation import

Change-Id: Ieacb413ff3ec0a3d55167ddc05b842c46f3f8e1c

Automatic translation import

Change-Id: I5a555c8f0c128838dd2767fb84d06ba4f90da8f0

Automatic translation import

Change-Id: I2845be54a06cf152819ef57fbc3ba846db3284b4

qcom-common: doze: add proximity wake

Change-Id: Ib02f4611e7b8bc09d540ca5c49aab68ef27f188b

Automatic translation import

Change-Id: I387927f7bd111b3511443790d0f64ae824fea291

Automatic translation import

Change-Id: I4b48f87da1678dc9d35bbed7af1714065f8d87b5

SamsungDoze: restore proximity wake preference on boot

Change-Id: I614772d6ff1005968a7f8f1ed0349e3878ddadf1

Automatic translation import

Change-Id: I67972dff42dd693ac2c954d65f3ed74e113e7016

Automatic translation import

Change-Id: I32640097b45dd4c7672556566c7d25d0d632b25f

SamsungDozeService: Prevent a pm wakeup with a timestamp in the future

Prevents:

java.lang.IllegalArgumentException: event time must not be in the future
at android.os.Parcel.readException(Parcel.java:1550)
        at android.os.Parcel.readException(Parcel.java:1499)
        at android.os.IPowerManager$Stub$Proxy.wakeUp(IPowerManager.java:550)
        at android.os.PowerManager.wakeUp(PowerManager.java:666)
        at com.cyanogenmod.settings.device.SamsungDozeService$SamsungProximitySensor.shouldPulse(SamsungDozeService.java:95)
        at com.cyanogenmod.settings.device.SamsungDozeService$SamsungProximitySensor.onSensorChanged(SamsungDozeService.java:75)
        at android.hardware.SystemSensorManager$SensorEventQueue.dispatchSensorEvent(SystemSensorManager.java:405)
        at android.os.MessageQueue.nativePollOnce(Native Method)
        at android.os.MessageQueue.next(MessageQueue.java:143)
        at android.os.Looper.loop(Looper.java:122)
        at android.app.ActivityThread.main(ActivityThread.java:5289)
        at java.lang.reflect.Method.invoke(Native Method)
        at java.lang.reflect.Method.invoke(Method.java:372)
        at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:904)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:699)

Change-Id: I8ed248271d67216e531b124bf27101fa538f1195
Signed-off-by: Brandon McAnsh <brandon.mcansh@gmail.com>

Automatic translation import

Change-Id: Ieaa8903f70277bc88e08dd4fd9475dd7a4b1f1a7

Automatic translation import

Change-Id: I872c9f85386fef4be890c74d5aecb03d9602f1ff

Automatic translation import

Change-Id: Ieea08c5ec5d135b3299d8a33c9841212bfcb5c0a

Automatic translation import

Change-Id: I13f4bef8b84cb2b7a722c9a6880ff094a25e0fef

SamsungDoze: fix typo

Change-Id: Id7716387688080b5ce0a99a4d968e210d8eed6f9

Automatic translation import

Change-Id: Id5bd372ba42e16510b4d3964d6ab36b348c72a43

Automatic translation import

Change-Id: I2cb48f1b616deb805d4cb1db7c9cf6daefe1db22

Automatic translation import

Change-Id: I4d4d3e2ec7c4be4050ccb8acae141f5db15cfb8d

Automatic translation import

Change-Id: I74738556eba3a67891c39508e518ee41c4428acd
(cherry picked from commit 3a26861e3243b4cbcbd40f70963f006aac7dd1b8)

doze: refactoring name Samsung to HTC

Change-Id: I547eb05f4aaa6ea736687dd64b1c37c587db7a62
Signed-off-by: José Adolfo Galdámez <josegalre@pac-rom.com>